export const jazzPlugin = 'http://jazz-soft.net/download/Jazz-Plugin/'
export const touchOSC_iOS = 'https://itunes.apple.com/au/app/touchosc/id288120394?mt=8'
export const touchOSC_android = 'https://play.google.com/store/apps/details?id=net.hexler.touchosc_a'
export const touchOSCbridge = 'http://hexler.net/software/touchosc#downloads'
export const touchOSCbridge_mac = 'http://hexler.net/mint/pepper/orderedlist/downloads/download.php?file=http%3A//hexler.net/pub/touchosc/touchosc-bridge-1.3.1-osx.zip'
export const touchOSCbridge_windows = 'http://hexler.net/mint/pepper/orderedlist/downloads/download.php?file=http%3A//hexler.net/pub/touchosc/touchosc-bridge-1.3.1-win32.zip'